[package]
name = "embed-struct"
description = "Rust library for embedding data structures"
version = "0.1.0"
edition = "2024"
authors = ["aegistudio (www@aegistudio.net)"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/aegistudio/embed-struct"

[dependencies]

[[example]]
name = "lrucache"
path = "examples/lrucache.rs"
crate-type = ["staticlib"]
test = true
